# This is a config for E2B sandbox template.
# You can use template ID (5zej89v7lmgu0j6q4qmh) or template name (wizio-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("wizio-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("wizio-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('wizio-nextjs-test-2')

team_id = "4fd248f5-23c4-47ec-af8a-3382b577f8a0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "wizio-nextjs-test-2"
template_id = "5zej89v7lmgu0j6q4qmh"
